### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by FedericoStra** [FedericoStra/RealContinuedFractions.jl#1]
Sources:
- https://encyclopediaofmath.org/wiki/Continued_fraction
- https://en.wikipedia.org/wiki/Continued_fraction
- https://en.wikipedia.org/wiki/Generalized_continued_fraction

Todo:

- [ ] conversions to numeric types: `Float64(::ContinuedFraction)`, ...
- [ ] canonical form (drop `1` in last position and increment previous term)
- [ ] find a suitable name for `q`: `quotients` is not good, `terms` or `coefficients` are better
- [ ] fix continued fraction of negative numbers (`modf` truncates towards `0`, not `-Inf`)
- [ ] implement `inv` ([hint](https://en.wikipedia.org/wiki/Continued_fraction#Of_reciprocals))
- [x] implement [convergents](https://en.wikipedia.org/wiki/Continued_fraction#Infinite_continued_fractions_and_convergents)
  - [ ] convergents with floating point: `convergent(Float64, cf)`?
  - [ ] optimize `BigInt` convergents using `Base.GMP.MPZ` directly (reduces allocations)
- [ ] implement continued fractions as an infinite iterator
- [ ] implement convergents as an iterator ([hint](https://en.wikipedia.org/wiki/Continued_fraction#Infinite_continued_fractions_and_convergents))
- [ ] [continuants](https://en.wikipedia.org/wiki/Continuant_(mathematics))
- [ ] output LaTeX in several [notations](https://en.wikipedia.org/wiki/Continued_fraction#Notations)
- [ ] [periodic continued fractions](https://en.wikipedia.org/wiki/Continued_fraction#Periodic_continued_fractions)
- [ ] [generalized continued fractions](https://en.wikipedia.org/wiki/Continued_fraction#Generalized_continued_fraction)
- [ ] [semiconvergents](https://en.wikipedia.org/wiki/Continued_fraction#Semiconvergents)
